config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # A visitor can see the list of all restaurants.
  # get 'restaurants', to: 'restaurants#index', as: :restaurants
  # # A visitor can add a new restaurant, and be redirected to the show view of that new restaurant.
  # get 'restaurants/new', to: 'restaurants#new', as: :new_restaurant
  # post 'restaurants', to: 'restaurants#create'
  # # A visitor can see the details of a restaurant, with all the reviews related to the restaurant.
  # get 'restaurants/:id', to: 'restaurants#show', as: :restaurant
  # A visitor can add a new review to a restaurant

  resources :restaurants, only: [ :index, :show, :edit, :create, :new, :update] do
    resources :reviews, only: [ :new, :create ]
  end

  # resources :restaurants do
  #   resources :reviews
  # end
    # GET "restaurants/38/reviews/new"
    # POST "restaurants/38/reviews"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  CATEGORY = ["chinese", "italian", "japanese", "french", "belgian"]
  validates :name, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true
  validates :category, inclusion: { in: CATEGORY }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :rating, inclusion: { in: [0, 1, 2, 3, 4, 5] }, numericality: { only_integer: true }
  validates :content, :rating, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update]

  def index
    @restaurants = Restaurant.all
  end

  def show
    # @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render 'restaurants/new'
    end
  end

  def edit
  end

  def update
    if @restaurant.update(restaurant_params)
      redirect_to restaurant_path(@restaurant)
    else
      render :edit
    end
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant, only: [:new]

  def new
    # we need @restaurant in our `simple_form_for`
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Add these line for detecting device width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <!-- [...] -->
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<div class="div">
  <%= simple_form_for @restaurant do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :phone_number%>
    <%= f.input :category, collection: Restaurant::CATEGORY %>
    <%= f.submit class: 'btn btn-primary mt-2' %>
  <% end %>
</div>

app/views/restaurants/edit.html.erb
<div class="container">
  <h1>Update <%= @restaurant.name%></h1>
  <%= render 'restaurants/form', restaurant: @restaurant%>
  <p><%= link_to '< Back', restaurant_path(@restaurant), class: 'btn-light' %></p>
</div>

app/views/restaurants/index.html.erb
<div class="container mt-5">
  <h1>Restaurants</h1>
  <% @restaurants.each do |restaurant| %>
  <ul>
    <%= link_to restaurant.name , restaurant_path(restaurant) %>
  </ul>
  <% end %>

  <i class="fas fa-plus"></i> <%=  link_to 'Add a new restaurant' , new_restaurant_path%>
</div>

app/views/restaurants/new.html.erb
<div class="container">
  <h1>Add new restaurant</h1>
  <%= render 'form' %>
</div>

app/views/restaurants/show.html.erb
<div class = "container">
  <h1><%= @restaurant.name %></h1>
  <div class="card" style="width: 18rem;">
    <%# <ul class="list-group list-group-flush"> %>
      <p class="card-header">Category: <%= @restaurant.category %></p>
      <p class="card-header">Address: <%= @restaurant.address %></p>
      <p class="card-header">Phone-number: <%= @restaurant.phone_number %></p>
    <%# </ul> %>
  </div>
  <%= link_to 'Edit', edit_restaurant_path(@restaurant) %> |
  <%= link_to 'Back', restaurants_path %> |
  <%= link_to 'Leave a review', new_restaurant_review_path(@restaurant) %>

  <ul class="list-group">
    <h2>Reviews</h2>
    <% @restaurant.reviews.each do |review| %>
      <li class="list-group-item">Rating:<%= review.rating %><%= review.content %></li>
    <% end %>
  </ul>

</div>

app/views/reviews/new.html.erb
<%= simple_form_for [ @restaurant, @review ] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating, collection: 0..5 %>
  <%= f.submit "Submit review", class: "btn btn-primary"%>
<% end %>